/*
* wall_following.c
*
* Contains the wall following algorithms for going straight and
* turning.
*/

/*
* Includes
*/
#include "wall_following.h"

/*
* straight(int x_front, int x_back)
*
* Contains the functionality to stay equidistant from each wall
* to keep the car going straight.
*
* Takes two distance inputs, from the front and back of one side
* of the car.
*
* Turning angle generated by PI algorithm based on the two input
* distances. turning_angle is a number from 0 to 255 with 127 being
* straight away.
*/

int straight(int x_front, int x_back){
  int turning_angle;
  turning_angle = STRAIGHT_ANGLE + (TURNING_FACTOR*(x_front-WALL_DISTANCE) + TURNING_FACTOR*(x_back-WALL_DISTANCE));
  return turning_angle;
}

/*
* turn(int x_front, int x_back)
*
* Follows the wall at a different distance than straight to accommodate
* for turn constraints on the track.
*
* Takes two distance inputs, x_front and x_back, that correspond
* to the distances from the wall on a side of the car.
*
* Turning angle generated by PI algorithm based on the two input
* distances. turning_angle is a number from 0 to 255 with 127 being 
* straight.
*/

int turn(int x_front, int x_back){
  int turning_angle;
  turning_angle = STRAIGHT_ANGLE + (TURNING_FACTOR*(x_front-TURN_DISTANCE) + TURNING_FACTOR*(x_back-TURN_DISTANCE));
  return turning_angle;
}

